
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:20 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:20 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/W3
      Id flags:  
      
      The output was:
      0
      .NET Framework용 Microsoft (R) Build Engine 버전 16.8.3+39993bd9d
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      빌드 시작: 2023-07-18 오후 2:08:47
      1 노드의 "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\3.27.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdC.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\3.27.0-rc5\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate"에 연결(touching)하고 있습니다.
      "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\3.27.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:01.72
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/3.27.0-rc5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:20 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/W3;/GR;/EHsc
      Id flags:  
      
      The output was:
      0
      .NET Framework용 Microsoft (R) Build Engine 버전 16.8.3+39993bd9d
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      빌드 시작: 2023-07-18 오후 2:08:49
      1 노드의 "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\3.27.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\3.27.0-rc5\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate"에 연결(touching)하고 있습니다.
      "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\3.27.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:01.46
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/3.27.0-rc5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:20 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-1xg45s"
      binary: "E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-1xg45s"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-1xg45s'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe" cmTC_65f76.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework용 Microsoft (R) Build Engine 버전 16.8.3+39993bd9d
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        빌드 시작: 2023-07-18 오후 2:08:52
        1 노드의 "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-1xg45s\\cmTC_65f76.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_65f76.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-1xg45s\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_65f76.dir\\Debug\\cmTC_65f76.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_65f76.dir\\Debug\\cmTC_65f76.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_65f76.dir\\Debug\\\\" /Fd"cmTC_65f76.dir\\Debug\\vc142.pdb" /Gd /TC /errorReport:queue "D:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ 최적화 컴파일러 버전 19.28.29336(x64)
          Copyright (c) Microsoft Corporation. All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_65f76.dir\\Debug\\\\" /Fd"cmTC_65f76.dir\\Debug\\vc142.pdb" /Gd /TC /errorReport:queue "D:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-1xg45s\\Debug\\cmTC_65f76.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-1xg45s/Debug/cmTC_65f76.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-1xg45s/Debug/cmTC_65f76.lib" /MACHINE:X64  /machine:x64 cmTC_65f76.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_65f76.vcxproj -> E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-1xg45s\\Debug\\cmTC_65f76.exe
        FinalizeBuildStatus:
          "cmTC_65f76.dir\\Debug\\cmTC_65f76.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_65f76.dir\\Debug\\cmTC_65f76.tlog\\cmTC_65f76.lastbuildstate"에 연결(touching)하고 있습니다.
        "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-1xg45s\\cmTC_65f76.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:01.92
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:20 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-oddzna"
      binary: "E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-oddzna"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-oddzna'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe" cmTC_ef6be.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework용 Microsoft (R) Build Engine 버전 16.8.3+39993bd9d
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        빌드 시작: 2023-07-18 오후 2:08:54
        1 노드의 "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-oddzna\\cmTC_ef6be.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_ef6be.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-oddzna\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_ef6be.dir\\Debug\\cmTC_ef6be.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_ef6be.dir\\Debug\\cmTC_ef6be.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ef6be.dir\\Debug\\\\" /Fd"cmTC_ef6be.dir\\Debug\\vc142.pdb" /Gd /TP /errorReport:queue "D:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ 최적화 컴파일러 버전 19.28.29336(x64)
          Copyright (c) Microsoft Corporation. All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ef6be.dir\\Debug\\\\" /Fd"cmTC_ef6be.dir\\Debug\\vc142.pdb" /Gd /TP /errorReport:queue "D:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-oddzna\\Debug\\cmTC_ef6be.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-oddzna/Debug/cmTC_ef6be.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/MMORPG_Server/protobuf-3.17.x/solution/CMakeFiles/CMakeScratch/TryCompile-oddzna/Debug/cmTC_ef6be.lib" /MACHINE:X64  /machine:x64 cmTC_ef6be.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_ef6be.vcxproj -> E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-oddzna\\Debug\\cmTC_ef6be.exe
        FinalizeBuildStatus:
          "cmTC_ef6be.dir\\Debug\\cmTC_ef6be.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_ef6be.dir\\Debug\\cmTC_ef6be.tlog\\cmTC_ef6be.lastbuildstate"에 연결(touching)하고 있습니다.
        "E:\\MMORPG_Server\\protobuf-3.17.x\\solution\\CMakeFiles\\CMakeScratch\\TryCompile-oddzna\\cmTC_ef6be.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:01.40
        
      exitCode: 0
...
